
spring:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  security:
    enabled: true

services:
  auth-service-url: ${AUTH_SERVICE_URL:http://auth-service:8081}
  customer-service-url: ${CUSTOMER_SERVICE_URL:http://customer-service:8082}

logging:
  level:
    com.zapcom: INFO
    org.springframework.cloud.gateway: INFO
    
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 30s
