
spring:
  redis:
    host: localhost
    port: 6379
  security:
    enabled: true

services:
  auth-service-url: http://localhost:8081
  customer-service-url: http://localhost:8082

logging:
  level:
    com.zapcom: DEBUG
    org.springframework.cloud.gateway: DEBUG
    
resilience4j:
  circuitbreaker:
    configs:
      default:
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 2s
