
server:
  port: 8080

spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379
  security:
    enabled: true

services:
  auth-service-url: http://localhost:8081
  customer-service-url: http://localhost:8082

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      authCircuitBreaker:
        baseConfig: default
      customerCircuitBreaker:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      authCircuitBreaker:
        baseConfig: default
      customerCircuitBreaker:
        baseConfig: default

logging:
  level:
    com.zapcom: DEBUG
    org.springframework.cloud.gateway: INFO
