
server:
  port: 8081

spring:
  application:
    name: authentication-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth-db

jwt:
  secret: TkRNeE1ETXhNelk1TWprM05ETmlaV1prT1RrNU9URmxORGM0TlRWbFpEazVPV0ZqTmpJME9HSTNNamM1TkRKa09HSmpPRGc=
  expirationMs: 3600000
